#
# created by
# Antonio Garcia-Uceda Juarez
# PhD student
# Medical Informatics
#
# created on 09/02/2018
# Last update: 09/02/2018
########################################################################################

import numpy as np
np.random.seed(2017)


DATADIR = '/home/antonio/Data/DLCST_Raw/'
BASEDIR = '/home/antonio/Results/AirwaySegmen_DLCST/'


# ******************** INPUT IMAGES PARAMETERS ********************
# MUST BE MULTIPLES OF 16
# FOUND VERY CONVENIENT THE VALUES 36, 76, 146, ...
(IMAGES_DEPTHZ, IMAGES_HEIGHT, IMAGES_WIDTH) = (104, 352, 240)
#(IMAGES_DEPTHZ, IMAGES_HEIGHT, IMAGES_WIDTH) = (224, 256, 256)

IMAGES_DIMS_X_Y   = (IMAGES_HEIGHT, IMAGES_WIDTH)
IMAGES_DIMS_Z_X_Y = (IMAGES_DEPTHZ, IMAGES_HEIGHT, IMAGES_WIDTH)

FORMATINTDATA   = np.int16
FORMATSHORTDATA = np.int16
FORMATREALDATA  = np.float32

FORMATIMAGESDATA     = FORMATINTDATA
FORMATMASKSDATA      = FORMATSHORTDATA
FORMATPHYSDISTDATA   = FORMATREALDATA
FORMATPROBABILITYDATA= FORMATREALDATA
FORMATFEATUREDATA    = FORMATREALDATA

SHUFFLEIMAGES   = True
NORMALIZEDATA   = False
FORMATINOUTDATA = 'numpy_gzbi'

ISCLASSIFICATIONCASE = False

MULTICLASSCASE = False

NUMCLASSESMASKS = 2

if ISCLASSIFICATIONCASE:
    FORMATXDATA = FORMATIMAGESDATA
    FORMATYDATA = FORMATMASKSDATA
else:
    FORMATXDATA = FORMATIMAGESDATA
    FORMATYDATA = FORMATPHYSDISTDATA
# ******************** INPUT IMAGES PARAMETERS ********************


# ******************** DATA DISTRIBUTION ********************
PROP_DATA_TRAINING   = 0.50
PROP_DATA_VALIDATION = 0.25
PROP_DATA_TESTING    = 0.25

DISTRIBUTE_RANDOM = False
DISTRIBUTE_FIXED_NAMES = False

NAME_IMAGES_TRAINING = []
NAME_IMAGES_VALIDATION = []
NAME_IMAGES_TESTING = []
# ******************** DATA DISTRIBUTION ********************


# ******************** PRE-PROCESSING PARAMETERS ********************
INVERTIMAGEAXIAL = False

MASKTOREGIONINTEREST = False

REDUCESIZEIMAGES = False

SIZEREDUCEDIMAGES = (256, 256)

CROPIMAGES = True

EXTENDSIZEIMAGES = False

CONSTRUCTINPUTDATADLCST = False

VOXELSBUFFERBORDER = (0, 0, 0, 0)
#VOXELSBUFFERBORDER = (30, 30, 0, 0)

#CROPSIZEBOUNDINGBOX = (240, 352, 480)
CROPSIZEBOUNDINGBOX = (352, 480)

CREATEIMAGESBATCHES = False

PROP_OVERLAP_Z_X_Y = (0.75, 0.0, 0.0)

VISUALPROCDATAINBATCHES = False
# ******************** PRE-PROCESSING PARAMETERS ********************


# ******************** TRAINING PARAMETERS ********************
#IMODEL         = 'Unet3D'
NUM_LAYERS      = 5
TYPE_NETWORK    = 'regression'
NUM_FEATMAPS_FIRSTLAYER = 16
ISUSE_DROPOUT   = False
ISUSE_BATCHNORMALIZE = False

ILOSSFUN    = 'MeanSquared_Tailored'
LISTMETRICS = []

DISABLE_CONVOL_POOLING_LASTLAYER = True

IOPTIMIZER = 'Adam'
NUM_EPOCHS = 1000
BATCH_SIZE = 1
LEARN_RATE = 1.0e-05

if CONSTRUCTINPUTDATADLCST:
    SLIDINGWINDOWIMAGES = False
else:
    SLIDINGWINDOWIMAGES = True

TRANSFORMATIONIMAGES = True

ROTATION_XY_RANGE = 10
ROTATION_XZ_RANGE = 5
ROTATION_YZ_RANGE = 5
HEIGHT_SHIFT_RANGE = 24
WIDTH_SHIFT_RANGE = 35
DEPTH_SHIFT_RANGE = 7
HORIZONTAL_FLIP = True
VERTICAL_FLIP = True
DEPTHZ_FLIP = True
ZOOM_RANGE = 0.0

ELASTICDEFORMATIONIMAGES = False

TYPEELASTICDEFORMATION = 'gridwise'

USETRANSFORMONVALIDATIONDATA = True

TYPEGPUINSTALLED = 'smaller_GPU'

USEMULTITHREADING = False
# ******************** TRAINING PARAMETERS ********************


# ******************** RESTART PARAMETERS ********************
USE_RESTARTMODEL = False

RESTART_MODELFILE = 'lastEpoch'

RESTART_ONLY_WEIGHTS = False

EPOCH_RESTART = 40
# ******************** RESTART PARAMETERS ********************


# ******************** POST-PROCESSING PARAMETERS ********************
TYPEDATAPREDICT = 'testing'

PREDICTION_MODELFILE = 'lastEpoch'

PREDICTACCURACYMETRICS = 'DiceCoefficient'

LISTPOSTPROCESSMETRICS = ['DiceCoefficient',
                          'TruePositiveRate',
                          'TrueNegativeRate',
                          'FalsePositiveRate',
                          'FalseNegativeRate']

FILTERPREDICTPROBMAPS = True

PROP_VALID_OUTUNET = 0.75

SAVEFEATMAPSLAYERS = False

NAMESAVEMODELLAYER = 'conv3d_18'

SAVEPREDICTMASKSLICES = False

CALCMASKSTHRESHOLDING = True

THRESHOLDVALUE = 0.5

ATTACHTRAQUEATOCALCMASKS = False

SAVETHRESHOLDIMAGES = True
# ******************** POST-PROCESSING PARAMETERS ********************
