
CODEDIR = '/home/antonio/Codes/mri_enhance/src/'
DATADIR = '/home/antonio/Data/MRIenhance_GRASE2CUBE_Processed/'
# DATADIR = '/data/scratch/agarcia/Data/MRIenhance/'         # cluster
BASEDIR = '/home/antonio/Results/MRIenhanceTests/'
# BASEDIR = '/data/scratch/agarcia/Results/MRIenhanceTests/' # cluster


# NAMES INPUT / OUTPUT DIR
NAME_RAW_IMAGES_RELPATH = 'Images/'
NAME_RAW_LABELS_RELPATH = 'Labels/'
NAME_RAW_ROIMASKS_RELPATH = 'RoiMasks/'
NAME_RAW_EXTRAIMAGES_RELPATH = 'NOUSE/'
NAME_RAW_EXTRALABELS_RELPATH = 'NOUSE/'
NAME_REFERENCE_FILES_RELPATH = 'Images/'
NAME_PROC_IMAGES_RELPATH = 'ImagesWorkData/'
NAME_PROC_LABELS_RELPATH = 'LabelsWorkData/'
NAME_PROC_EXTRALABELS_RELPATH = 'CenlinesWorkData/'
NAME_CROP_BOUNDBOXES_FILE = 'cropBoundingBoxes_images.npy'
NAME_RESCALE_FACTORS_FILE = 'rescaleFactors_images.npy'
NAME_REFERENCE_KEYS_PROCIMAGE_FILE = 'referenceKeys_procimages.npy'
NAME_TRAININGDATA_RELPATH = 'TrainingData/'
NAME_VALIDATIONDATA_RELPATH = 'ValidationData/'
NAME_TESTINGDATA_RELPATH = 'TestingData/'
NAME_MODELSRUN_RELPATH = 'Models/'
NAME_LOSSHISTORY_FILE = 'losshistory.csv'
NAME_CONFIG_PARAMS_FILE = 'configparams.txt'
NAME_TRAINDATA_LOGFILE = 'traindatafiles.txt'
NAME_VALIDDATA_LOGFILE = 'validdatafiles.txt'
NAME_TEMPO_POSTERIORS_RELPATH = 'Predictions/PosteriorsWorkData/'
NAME_POSTERIORS_RELPATH = 'Predictions/Posteriors/'
NAME_REFERENCE_KEYS_POSTERIORS_FILE = 'Predictions/referenceKeys_posteriors.npy'
NAME_PRED_RESULT_METRICS_FILE = 'Predictions/result_metrics.csv'


# PREPROCESSING
IS_BINARY_TRAIN_MASKS = False
IS_NORMALIZE_DATA = False
IS_MASK_REGION_INTEREST = False
IS_CROP_IMAGES = False
IS_RESCALE_IMAGES = False
IS_MERGE_TWO_IMAGES_AS_CHANNELS = False


# DISTRIBUTE DATA TRAIN / VALID / TEST
PROPDATA_TRAIN_VALID_TEST = (0.65, 0.15, 0.20)


# CHOOSE DL BACKEND
TYPE_DNNLIB_USED = 'Keras'
IS_MODEL_GPU = True
IS_MODEL_HALFPREC = False


# TRAINING MODELS
SIZE_IN_IMAGES = (288, 288, 96)
MAX_TRAIN_IMAGES = 500
MAX_VALID_IMAGES = 200
TYPE_NETWORK = 'UNet3DPlugin3levels'    # 'UNet3DPlugin5levels'
NET_NUM_FEATMAPS = 16
TYPE_OPTIMIZER = 'Adam'
LEARN_RATE = 1.0e-04
TYPE_LOSS = 'DSSIM'         # 'Perceptual' #'MultiScaleSSIM'
WEIGHT_COMBINED_LOSS = 1000.0
LAYERS_VGG16_LOSS_PERCEPTUAL = ['block1_conv1', 'block2_conv1', 'block3_conv1']
WEIGHTS_VGG16_LOSS_PERCEPTUAL = [0.65, 0.30, 0.05]
PROP_REDSIZE_VGG16_LOSS_PERCEPTUAL = 0.33
LIST_TYPE_METRICS = ['DSSIM']
BATCH_SIZE = 1
NUM_EPOCHS = 500
IS_VALID_CONVOLUTIONS = False
FREQ_SAVE_CHECK_MODELS = 10
FREQ_VALIDATE_MODELS = 2
IS_USE_VALIDATION_DATA = True
IS_SHUFFLE_TRAINDATA = True
MANUAL_SEED_TRAIN = None


# DATA AUGMENTATION IN TRAINING
IS_GENERATE_PATCHES = False
TYPE_GENERATE_PATCHES = 'slide_window'
PROP_OVERLAP_SLIDE_WINDOW = (0.5, 0.5, 0.5)
NUM_RANDOM_PATCHES_EPOCH = 4
IS_TRANSFORM_IMAGES = True
TYPE_TRANSFORM_IMAGES = 'rigid_trans'
TRANS_RIGID_ROTATION_RANGE = (0.0, 0.0, 0.0)    # (plane_XY, plane_XZ, plane_YZ)
TRANS_RIGID_SHIFT_RANGE = (0.0, 0.0, 0.0)       # (width, height, depth)
TRANS_RIGID_FLIP_DIRS = (True, True, True)      # (horizontal, vertical, axialdir)
TRANS_RIGID_ZOOM_RANGE = 0.0                    # scale between (1 - val, 1 + val)
TRANS_RIGID_FILL_MODE = 'nearest'


# NOT USED - TRAINING MODELS
# NET_NUM_LEVELS = 3
# TYPE_ACTIVATE_HIDDEN = 'relu'
# TYPE_ACTIVATE_OUTPUT = 'linear'
# NET_IS_USE_DROPOUT = False
# NET_IS_USE_BATCHNORMALIZE = False
# IS_DISABLE_CONVOL_POOLING_LASTLAYER = False
# IS_MULTITHREADING = False


# PREDICTIONS / POST-PROCESSING
PROP_OVERLAP_SLIDE_WINDOW_TEST = (0.5, 0.5, 0.5)
LIST_TYPE_METRICS_RESULT = ['SNR', 'PSNR', 'SSIM']
